include: package:flutter_lints/flutter.yaml

linter:
  # https://dart.dev/guides/language/analysis-options
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_type_to_string: true
    empty_statements: true
    always_declare_return_types: true
    annotate_overrides: true