coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 10%

comment:
  layout: "condensed_header, diff"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: true