name: dart_dart
description: "A Dart Scoreboard written in Dart"
homepage: "https://da-kai.github.io/DartDart/"
repository: "https://github.com/da-Kai/DartDart"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.2

flutter_launcher_icons:
  image_path_android: "assets/icons/icon-colored-1024.png"
  image_path_ios: "assets/icons/icon-colored-1024.png"
  android: true
  ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon-android-fg-1024.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icons/icon-colored-1024.png"
    background_color: "#3e77bd"
    theme_color: "#3e77bd"
  windows:
    generate: true
    image_path: "assets/icons/icon-colored-1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon-macos-1024.png"

flutter:
  assets:
    - 'assets/images/dart_board-1024.png'
  uses-material-design: true
  fonts:
    - family: dartdart
      fonts:
        - asset: assets/fonts/dartdart/dartdart.ttf
    - family: oswald
      fonts:
        - asset: assets/fonts/oswald/oswald-regular.ttf
        - asset: assets/fonts/oswald/oswald-bold.ttf
          weight: 900
        - asset: assets/fonts/oswald/oswald-medium.ttf
          weight: 500
        - asset: assets/fonts/oswald/oswald-light.ttf
          weight: 300
    - family: mitr
      fonts:
        - asset: assets/fonts/mitr/mitr-regular.ttf
        - asset: assets/fonts/mitr/mitr-bold.ttf
          weight: 900
        - asset: assets/fonts/mitr/mitr-medium.ttf
          weight: 500
        - asset: assets/fonts/mitr/mitr-light.ttf
          weight: 300
    - family: titillium
      fonts:
        - asset: assets/fonts/titillium_web/titillium-web-regular.ttf
        - asset: assets/fonts/titillium_web/titillium-web-bold.ttf
          weight: 900
        - asset: assets/fonts/titillium_web/titillium-web-bold-italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/titillium_web/titillium-web-italic.ttf
          style: italic
        - asset: assets/fonts/titillium_web/titillium-web-light.ttf
          weight: 200
        - asset: assets/fonts/titillium_web/titillium-web-light-italic.ttf
          weight: 200
          style: italic