name: dart_dart
description: "A Dart Scoreboard written in Dart"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/icons/icon-colored-1024.png"
  image_path_ios: "assets/icons/icon-colored-1024.png"
  android: true
  ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon-android-fg-1024.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icons/icon-colored-1024.png"
    background_color: "#3e77bd"
    theme_color: "#3e77bd"
  windows:
    generate: true
    image_path: "assets/icons/icon-colored-1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon-macos-1024.png"

flutter:
  uses-material-design: true
  fonts:
    - family: dartdart
      fonts:
        - asset: assets/fonts/dartdart/dartdart.ttf
    - family: oswald
      fonts:
        - asset: assets/fonts/oswald/oswald-Regular.ttf
        - asset: assets/fonts/oswald/oswald-Bold.ttf
          weight: 900
        - asset: assets/fonts/oswald/oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/oswald/oswald-Light.ttf
          weight: 300
    - family: mitr
      fonts:
        - asset: assets/fonts/mitr/Mitr-Regular.ttf
        - asset: assets/fonts/mitr/Mitr-Bold.ttf
          weight: 900
        - asset: assets/fonts/mitr/Mitr-Medium.ttf
          weight: 500
        - asset: assets/fonts/mitr/Mitr-Light.ttf
          weight: 300
    - family: titilliumWeb
      fonts:
        - asset: assets/fonts/titillium_web/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium_web/TitilliumWeb-Bold.ttf
          weight: 900
        - asset: assets/fonts/titillium_web/TitilliumWeb-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/titillium_web/TitilliumWeb-Italic.ttf
          style: italic
        - asset: assets/fonts/titillium_web/TitilliumWeb-Light.ttf
          weight: 200
        - asset: assets/fonts/titillium_web/TitilliumWeb-LightItalic.ttf
          weight: 200
          style: italic