name: Build DartDart
on:
  push:
    branches:
      - main

jobs:
  build-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release
      - run: mv ./build/app/outputs/flutter-apk/app-release.apk ./dart-dart.apk

      - uses: actions/upload-artifact@v4
        with:
          name: dart-dart-android
          path: ./dart-dart.apk