name: Build DartDart
on:
  push:
    branches: [ main, develop ]

jobs:
  build-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter --version
          flutter pub get
          mkdir -p build/artifact
          dart run flutter_launcher_icons
      - run: |
          flutter build apk --no-pub --release
          mv build/app/outputs/flutter-apk/app-release.apk build/artifact/dart-dart.apk
      - run: | 
          flutter build appbundle --no-pub --release
          mv build/app/outputs/bundle/release/app-release.aab build/artifact/dart-dart.aab

      - uses: actions/upload-artifact@v4
        with:
          name: dart-dart-android
          path: build/artifact