name: Test DartDart
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - run: flutter pub get
      - run: flutter test
      - run: dart analyze