name: Test DartDart
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter --version
          flutter config --no-cli-animations
          flutter config --no-analytics
          flutter pub get

      - run: flutter test --coverage --coverage-path=lcov.info
      
      - run: flutter analyze

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: da-Kai/DartDart
